language: smalltalk
services:
- docker
env:
- SQUEAK_VERSION=Trunk
- SQUEAK_VERSION=5.3
smalltalk: Squeak64-${SQUEAK_VERSION}
before_script:
- 'test $TRAVIS_BRANCH = master || export DEBUG_FIGURES=true

'
- set -o pipefail
script:
- false
jobs:
  include:
  - stage: deploy
    if: branch = master AND type = push
    name: GitHub Release
    env: SQUEAK_VERSION=
    language: minimal
    install: skip
    script: "./build_scripts/gdrive.sh download"
    deploy:
      provider: releases
      file_glob: true
      file: SBE_*.pdf
      api_key: "$GH_OAUTH_TOKEN"
      skip_cleanup: true
      on:
        all_branches: true
notifications:
  email:
    if: type = cron
  slack:
    rooms:
      - hpi-swa-teaching:MgW9Kp7SzvqtTyf0Gr2uBMu1#squeak
    on_failure: always
