language: generic
sudo: true
addons:
  apt:
    packages:
    - texlive-full
script:
- make
deploy:
  provider: releases
  api_key:
    secure: NonbhAGQoWcE2vHYVXvLJAK9YuvW0g3VnEVcjqqGIf+LQEP68FolnBfMpKL5gLg1p8nmsyU5z+zAFapQUxvSVxWzLhsSLGlyZmWlcyrt+zZwCxNaPGB0RvuOLhZABaPizAp2zLbf0b8s8v38ToTl7fLCamf39fjC1O4oEtyXuD3kWaUpj8S0hXbz9/SYJLSNyKvCXzjjfCFf8nG3B/QksoSGKaGVP0A8uRG3yJR3cWTJKYOhjLg2+utXaedW/MwnLz1re4bBdH2EwXJK90A9JhjgeH1hBAc57dXN3hCMBWu/9uvP9/+Vlv5w6W6k4zTPuLow28xIeT1baBCL7PXgqBwCK/u6pXWSZVIYZTfoxRNhff9rzD1Jvj2J1fEzm0IqL8Zvz/v7N7hoVtt7fOt2deStb56xWKCL0/EKCAd56EtXKmSQdSMSgcEoQnyLb+pIF0+AroVrLCKqT0z/tNugtRBaTrlUT4r3QGKiIGme3SlOFqeBVaa8M+YDB2ZGyp0K/EGuL8EPmzfLdh+ajlXfFPSNvmOmAOTeTbURtxPFblDsJhahrCaRIs/b6DrQNqWI4eAJomd9+Fs6CwpHCLg9heuwxSDZcbbjkeJ7svFIEMXbUJAprkUGoJhZ4hj3u6mC2wpG30x3WAZq32KuNb3hDN/V+X0Yop1mM/3WyOF8h8c=
  file: SBE.pdf
  on:
    repo: MrModder/SqueakByExample-english
  branches:
    only: master
