language: smalltalk
services:
- docker

env:
  - SQUEAK_VERSION=Trunk
  - SQUEAK_VERSION=5.3

smalltalk: "Squeak64-${SQUEAK_VERSION}"

before_script:
- | # Ignore missing figures during PDF build
  test $TRAVIS_BRANCH = master || export DEBUG_FIGURES=true
- set -o pipefail
script:
- false # debug
- smalltalkci .smalltalk.ston
- make | ./build_scripts/travis_fold Compiling PDF ...
- mv SBE.pdf "SBE_${SQUEAK_VERSION}.pdf"
- | # Upload PDF file to Google Drive
  if [ "$TRAVIS_PULL_REQUEST" = false ]
  then
    ./build_scripts/gdrive.sh upload "SBE_${SQUEAK_VERSION}.pdf"
  fi

jobs:
  include:
    - stage: deploy
      if: branch = master AND type = push
      name: GitHub Release
      env: SQUEAK_VERSION=
      language: minimal
      install: skip
      script: ./build_scripts/gdrive.sh download
      deploy:
        provider: releases
        file_glob: true
        file: SBE_*.pdf
        api_key: $GH_OAUTH_TOKEN
        skip_cleanup: true
        on:
          all_branches: true

notifications:
  email:
    if: type = cron
  slack:
    rooms:
      secure: q44JZ9USsVHqq4ww1lx2mClEdUCnpDLGaQozcN328J0GR9pWEud3YE8Xy2hxwaEOLfkamsPdjhMQTUBVd5DkYD07nLiFS6tv12AOse7cNI/hebtcMNRLsR2hm5njuadK/frRVY1oSWXL/3FkffDspbi5GzLjPTj4mZVw+Wixv+ksrk6Q27DwxJttvzpMQD+nFDKq3Br9f4Xil4VRXN7RPs2GIuyg8FHiRuS0LpPFffqTOEDc1e+eZGjekDGljIbDdR4dL+uZuZtvXOrMADmRsTbPr7IWS776QT6gP3YTQ3+1gatdd2WZS6oZhE7+mqEXBIKWni8yawazL4NbQIsJyD9kbF1a+nJqwStQMO3NpuROdgDQQtEhOeDsFStIj7OU1Rh7GxTrUM0r09mhg9MtK9oU2/1DWMKqwXoJt1TxUIT4wVih2OL9uCXVhS9wYBWqdEMrNqOvVGt9hosHOKTJt5AsU18BqxeFtHQCjDmG0nhLfF7zP7X5x1ezoOB01L/DYfv3LHGFDoKYodBXvwnDRhhUWAleYymZm/SmhZ2vr29dmDiV0DfGoD5yINyNpu6DBYD7zSS16fRzNmtxxRBMjgPiZaY2boCL8Udy2zQ2ltTixmNnF8YbT+bIdBvnAs15Zr8FQ+TTGnHcspSn5NCCN/3qTyhca3TVBPJ7NP+aMeg=
    if: type = cron
