language: smalltalk
services:
- docker
env:
- SQUEAK_VERSION=Trunk
- SQUEAK_VERSION=5.3
smalltalk: Squeak64-${SQUEAK_VERSION}
before_script:
- 'test $TRAVIS_BRANCH = master || export DEBUG_FIGURES=true

'
- set -o pipefail
script:
- false
jobs:
  include:
  - stage: deploy
    if: branch = master AND type = push
    name: GitHub Release
    env: SQUEAK_VERSION=
    language: minimal
    install: skip
    script: "./build_scripts/gdrive.sh download"
    deploy:
      provider: releases
      file_glob: true
      file: SBE_*.pdf
      api_key: "$GH_OAUTH_TOKEN"
      skip_cleanup: true
      on:
        all_branches: true
notifications:
  email:
    if: type = cron
  slack:
    rooms:
      - secure: k8xcqMLoK4i+EEFmjOFHMI0f5/bnTQtt/7aUrsmphVXUkBqAXEtka4C4baMPP+2vH44CM5HRlTcfYPeKxFxuowt7H1JFoIiKJpaqMbMm+jQt9uYk9UNvUGxOI1I33KnI2/lTbATRoKj9/+C48lgDcoL07SQ1Dm7rib9Nnj3VUuhcENicFuFWdHnJM3qrKs6Bu2ZgJa7zHvnho0F8wN1tRcc1fJK1ygw2rVyAvNmdOVvC78p4eOVDW1dy58UQef5ufXqSfNKZITj34uOUlZjug34MvWRwGiHFsqpmhbCc0133Q+tsdV3FlRYkmvCup/qKuC2dJQeARR5bSqaYwSRGe7g6X7Lfv0M8mbGboQjQ+9FCTY4TxHnaVIxVa+YsC2YDXALsZWbbOFXYjbXPULXZEghPlQUf3UfUehgJ/ivKLSC6YR7h3V9ad7A1V7IQSD/bdjh4FYOxlryime1/YCKZPpF9BBfZ+f/D2o6MkeY4o06qaEMCrbcA7ovVDMTSY3h2QVgFuTIAmzPlMnu7yGSYLgVebJvx5SKE9CnqXqHevAAmqY4Fv860Iyps1U1Qp2byD63e5VKUOA6NLhr8EhCZVF7c8QIt2H5FGGkH4FDs7fNKYJIgPQ/JtCDAhumwwxiHNElwVGobpJ0WAdZMRpt/4B+ZkTlzdH2fuxOvfYspGd8=
    on_failure: always
