name: ⚖ Compare

on:
  workflow_run:
    workflows: ["📕 Make Book"]
    types: [completed]

jobs:
  query-github:
    runs-on: ubuntu-latest
    outputs:
      prs: ${{ steps.find-prs.outputs.result }}
      prerelease: ${{ steps.find-latest-prerelease.outputs.result }}
    steps:
      - id: find-prs
        uses: actions/github-script@v4
        with:
          github-token: ${{ github.token }}
          script: |
            const query = `query ($owner: String!, $name: String!, $baseRefName: String!) {
              repository(owner: $owner, name: $name) {
                pullRequests(first: 100, baseRefName: $baseRefName) {
                  nodes {
                    id
                    headRefName
                    number
                  }
                }
              }
            }`
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              baseRefName: 'master'
            }
            const result = await github.graphql(query, variables);
            return result.repository.pullRequests.nodes
      - id: find-latest-prerelease
        uses: actions/github-script@v4
        with:
          github-token: ${{ github.token }}
          script: |
            const query = `query ($owner: String!, $name: String!) {
              repository(owner: $owner, name: $name) {
                releases(first: 10, orderBy: {field: CREATED_AT, direction: DESC}) {
                  nodes {
                    isPrerelease,
                    id
                  }
                }
              }
            }`
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo
            }
            const result = await github.graphql(query, variables);
            return result.repository.releases.nodes.filter(y => y.isPrerelease)[0]
  diff:
    needs: query-github
    strategy:
      matrix:
        pr: ${{ fromJson(needs.query-github.outputs.prs) }}
        smalltalk: [Trunk, 5.3]
    runs-on: ubuntu-latest
    steps:
      - name: Load latest prereleases
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: ${{ fromJson(needs.query-github.outputs.prerelease).id }}
          file: SBE-${{ matrix.smalltalk }}.pdf
          target: SBE-${{ matrix.smalltalk }}.old.pdf
          token: ${{ github.token }}
      - name: Setup diff-pdf
        run: |
          sudo apt-get update
          sudo apt-get install -y make automake g++
          sudo apt-get install -y libpoppler-glib-dev poppler-utils libwxgtk3.0-gtk3-dev
          wget -c https://github.com/vslavik/diff-pdf/releases/download/v0.5/diff-pdf-0.5.tar.gz -O - | tar -xz && mv diff-pdf{-0.5,}
          cd diff-pdf
          ./bootstrap
          ./configure
          make
          sudo make install
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token }}
          run_id: ${{ github.event.workflow_run.id }}
          name: book-${{ matrix.smalltalk }}
          path: SBE-${{ matrix.smalltalk }}.pdf
      - name: Compare PDFs
        run: |
           diff-pdf --skip-identical --mark-differences --output-diff=diff-${{ matrix.smalltalk }}.pdf SBE-${{ matrix.smalltalk }}.old.pdf SBE-${{ matrix.smalltalk }}.pdf
      - name: Upload diffs
        uses: actions/upload-artifact@master
        with:
          name: diff-${{ matrix.smalltalk }}
          path: diff-${{ matrix.smalltalk }}.pdf
      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ github.token }}
          script: |
            github.issues.createComment({
              issue_number: ${{ matrix.pr.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
                # PDF diff
                
                👋 Hey there, I created visual diff of the PDF! You can find it in the Actions section of the repository.
              `
            })
